/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccordionRouteImport } from './routes/accordion'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as BoxDetailRouteImport } from './routes/box-detail'
import { Route as ButtonRouteImport } from './routes/button'
import { Route as CheckboxRouteImport } from './routes/checkbox'
import { Route as ChipRouteImport } from './routes/chip'
import { Route as ClickableOptionRouteImport } from './routes/clickable-option'
import { Route as CopyTooltipRouteImport } from './routes/copy-tooltip'
import { Route as CustomerCardRouteImport } from './routes/customer-card'
import { Route as DatePickerRouteImport } from './routes/date-picker'
import { Route as DropdownRouteImport } from './routes/dropdown'
import { Route as EmptyPageRouteImport } from './routes/empty-page'
import { Route as FieldRouteImport } from './routes/field'
import { Route as GroupIconRouteImport } from './routes/group-icon'
import { Route as InputStepperRouteImport } from './routes/input-stepper'
import { Route as LabelRouteImport } from './routes/label'
import { Route as ListItemRouteImport } from './routes/list-item'
import { Route as ModalRouteImport } from './routes/modal'
import { Route as OverviewItemRouteImport } from './routes/overview-item'
import { Route as PageTitleRouteImport } from './routes/page-title'
import { Route as ProgressBarRouteImport } from './routes/progress-bar'
import { Route as RadioGroupRouteImport } from './routes/radio-group'
import { Route as SliderRouteImport } from './routes/slider'
import { Route as SnackbarRouteImport } from './routes/snackbar'
import { Route as SubHeaderRouteImport } from './routes/sub-header'
import { Route as TabMenuRouteImport } from './routes/tab-menu'
import { Route as ToggleRouteImport } from './routes/toggle'
import { Route as TooltipRouteImport } from './routes/tooltip'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccordionRoute = AccordionRouteImport.update({
  id: '/accordion',
  path: '/accordion',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxDetailRoute = BoxDetailRouteImport.update({
  id: '/box-detail',
  path: '/box-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonRoute = ButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckboxRoute = CheckboxRouteImport.update({
  id: '/checkbox',
  path: '/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ChipRoute = ChipRouteImport.update({
  id: '/chip',
  path: '/chip',
  getParentRoute: () => rootRouteImport,
} as any)
const ClickableOptionRoute = ClickableOptionRouteImport.update({
  id: '/clickable-option',
  path: '/clickable-option',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyTooltipRoute = CopyTooltipRouteImport.update({
  id: '/copy-tooltip',
  path: '/copy-tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCardRoute = CustomerCardRouteImport.update({
  id: '/customer-card',
  path: '/customer-card',
  getParentRoute: () => rootRouteImport,
} as any)
const DatePickerRoute = DatePickerRouteImport.update({
  id: '/date-picker',
  path: '/date-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const DropdownRoute = DropdownRouteImport.update({
  id: '/dropdown',
  path: '/dropdown',
  getParentRoute: () => rootRouteImport,
} as any)
const EmptyPageRoute = EmptyPageRouteImport.update({
  id: '/empty-page',
  path: '/empty-page',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIconRoute = GroupIconRouteImport.update({
  id: '/group-icon',
  path: '/group-icon',
  getParentRoute: () => rootRouteImport,
} as any)
const InputStepperRoute = InputStepperRouteImport.update({
  id: '/input-stepper',
  path: '/input-stepper',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelRoute = LabelRouteImport.update({
  id: '/label',
  path: '/label',
  getParentRoute: () => rootRouteImport,
} as any)
const ListItemRoute = ListItemRouteImport.update({
  id: '/list-item',
  path: '/list-item',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalRoute = ModalRouteImport.update({
  id: '/modal',
  path: '/modal',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewItemRoute = OverviewItemRouteImport.update({
  id: '/overview-item',
  path: '/overview-item',
  getParentRoute: () => rootRouteImport,
} as any)
const PageTitleRoute = PageTitleRouteImport.update({
  id: '/page-title',
  path: '/page-title',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressBarRoute = ProgressBarRouteImport.update({
  id: '/progress-bar',
  path: '/progress-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioGroupRoute = RadioGroupRouteImport.update({
  id: '/radio-group',
  path: '/radio-group',
  getParentRoute: () => rootRouteImport,
} as any)
const SliderRoute = SliderRouteImport.update({
  id: '/slider',
  path: '/slider',
  getParentRoute: () => rootRouteImport,
} as any)
const SnackbarRoute = SnackbarRouteImport.update({
  id: '/snackbar',
  path: '/snackbar',
  getParentRoute: () => rootRouteImport,
} as any)
const SubHeaderRoute = SubHeaderRouteImport.update({
  id: '/sub-header',
  path: '/sub-header',
  getParentRoute: () => rootRouteImport,
} as any)
const TabMenuRoute = TabMenuRouteImport.update({
  id: '/tab-menu',
  path: '/tab-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ToggleRoute = ToggleRouteImport.update({
  id: '/toggle',
  path: '/toggle',
  getParentRoute: () => rootRouteImport,
} as any)
const TooltipRoute = TooltipRouteImport.update({
  id: '/tooltip',
  path: '/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accordion': typeof AccordionRoute
  '/avatar': typeof AvatarRoute
  '/box-detail': typeof BoxDetailRoute
  '/button': typeof ButtonRoute
  '/checkbox': typeof CheckboxRoute
  '/chip': typeof ChipRoute
  '/clickable-option': typeof ClickableOptionRoute
  '/copy-tooltip': typeof CopyTooltipRoute
  '/customer-card': typeof CustomerCardRoute
  '/date-picker': typeof DatePickerRoute
  '/dropdown': typeof DropdownRoute
  '/empty-page': typeof EmptyPageRoute
  '/field': typeof FieldRoute
  '/group-icon': typeof GroupIconRoute
  '/input-stepper': typeof InputStepperRoute
  '/label': typeof LabelRoute
  '/list-item': typeof ListItemRoute
  '/modal': typeof ModalRoute
  '/overview-item': typeof OverviewItemRoute
  '/page-title': typeof PageTitleRoute
  '/progress-bar': typeof ProgressBarRoute
  '/radio-group': typeof RadioGroupRoute
  '/slider': typeof SliderRoute
  '/snackbar': typeof SnackbarRoute
  '/sub-header': typeof SubHeaderRoute
  '/tab-menu': typeof TabMenuRoute
  '/toggle': typeof ToggleRoute
  '/tooltip': typeof TooltipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accordion': typeof AccordionRoute
  '/avatar': typeof AvatarRoute
  '/box-detail': typeof BoxDetailRoute
  '/button': typeof ButtonRoute
  '/checkbox': typeof CheckboxRoute
  '/chip': typeof ChipRoute
  '/clickable-option': typeof ClickableOptionRoute
  '/copy-tooltip': typeof CopyTooltipRoute
  '/customer-card': typeof CustomerCardRoute
  '/date-picker': typeof DatePickerRoute
  '/dropdown': typeof DropdownRoute
  '/empty-page': typeof EmptyPageRoute
  '/field': typeof FieldRoute
  '/group-icon': typeof GroupIconRoute
  '/input-stepper': typeof InputStepperRoute
  '/label': typeof LabelRoute
  '/list-item': typeof ListItemRoute
  '/modal': typeof ModalRoute
  '/overview-item': typeof OverviewItemRoute
  '/page-title': typeof PageTitleRoute
  '/progress-bar': typeof ProgressBarRoute
  '/radio-group': typeof RadioGroupRoute
  '/slider': typeof SliderRoute
  '/snackbar': typeof SnackbarRoute
  '/sub-header': typeof SubHeaderRoute
  '/tab-menu': typeof TabMenuRoute
  '/toggle': typeof ToggleRoute
  '/tooltip': typeof TooltipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accordion': typeof AccordionRoute
  '/avatar': typeof AvatarRoute
  '/box-detail': typeof BoxDetailRoute
  '/button': typeof ButtonRoute
  '/checkbox': typeof CheckboxRoute
  '/chip': typeof ChipRoute
  '/clickable-option': typeof ClickableOptionRoute
  '/copy-tooltip': typeof CopyTooltipRoute
  '/customer-card': typeof CustomerCardRoute
  '/date-picker': typeof DatePickerRoute
  '/dropdown': typeof DropdownRoute
  '/empty-page': typeof EmptyPageRoute
  '/field': typeof FieldRoute
  '/group-icon': typeof GroupIconRoute
  '/input-stepper': typeof InputStepperRoute
  '/label': typeof LabelRoute
  '/list-item': typeof ListItemRoute
  '/modal': typeof ModalRoute
  '/overview-item': typeof OverviewItemRoute
  '/page-title': typeof PageTitleRoute
  '/progress-bar': typeof ProgressBarRoute
  '/radio-group': typeof RadioGroupRoute
  '/slider': typeof SliderRoute
  '/snackbar': typeof SnackbarRoute
  '/sub-header': typeof SubHeaderRoute
  '/tab-menu': typeof TabMenuRoute
  '/toggle': typeof ToggleRoute
  '/tooltip': typeof TooltipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accordion'
    | '/avatar'
    | '/box-detail'
    | '/button'
    | '/checkbox'
    | '/chip'
    | '/clickable-option'
    | '/copy-tooltip'
    | '/customer-card'
    | '/date-picker'
    | '/dropdown'
    | '/empty-page'
    | '/field'
    | '/group-icon'
    | '/input-stepper'
    | '/label'
    | '/list-item'
    | '/modal'
    | '/overview-item'
    | '/page-title'
    | '/progress-bar'
    | '/radio-group'
    | '/slider'
    | '/snackbar'
    | '/sub-header'
    | '/tab-menu'
    | '/toggle'
    | '/tooltip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accordion'
    | '/avatar'
    | '/box-detail'
    | '/button'
    | '/checkbox'
    | '/chip'
    | '/clickable-option'
    | '/copy-tooltip'
    | '/customer-card'
    | '/date-picker'
    | '/dropdown'
    | '/empty-page'
    | '/field'
    | '/group-icon'
    | '/input-stepper'
    | '/label'
    | '/list-item'
    | '/modal'
    | '/overview-item'
    | '/page-title'
    | '/progress-bar'
    | '/radio-group'
    | '/slider'
    | '/snackbar'
    | '/sub-header'
    | '/tab-menu'
    | '/toggle'
    | '/tooltip'
  id:
    | '__root__'
    | '/'
    | '/accordion'
    | '/avatar'
    | '/box-detail'
    | '/button'
    | '/checkbox'
    | '/chip'
    | '/clickable-option'
    | '/copy-tooltip'
    | '/customer-card'
    | '/date-picker'
    | '/dropdown'
    | '/empty-page'
    | '/field'
    | '/group-icon'
    | '/input-stepper'
    | '/label'
    | '/list-item'
    | '/modal'
    | '/overview-item'
    | '/page-title'
    | '/progress-bar'
    | '/radio-group'
    | '/slider'
    | '/snackbar'
    | '/sub-header'
    | '/tab-menu'
    | '/toggle'
    | '/tooltip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccordionRoute: typeof AccordionRoute
  AvatarRoute: typeof AvatarRoute
  BoxDetailRoute: typeof BoxDetailRoute
  ButtonRoute: typeof ButtonRoute
  CheckboxRoute: typeof CheckboxRoute
  ChipRoute: typeof ChipRoute
  ClickableOptionRoute: typeof ClickableOptionRoute
  CopyTooltipRoute: typeof CopyTooltipRoute
  CustomerCardRoute: typeof CustomerCardRoute
  DatePickerRoute: typeof DatePickerRoute
  DropdownRoute: typeof DropdownRoute
  EmptyPageRoute: typeof EmptyPageRoute
  FieldRoute: typeof FieldRoute
  GroupIconRoute: typeof GroupIconRoute
  InputStepperRoute: typeof InputStepperRoute
  LabelRoute: typeof LabelRoute
  ListItemRoute: typeof ListItemRoute
  ModalRoute: typeof ModalRoute
  OverviewItemRoute: typeof OverviewItemRoute
  PageTitleRoute: typeof PageTitleRoute
  ProgressBarRoute: typeof ProgressBarRoute
  RadioGroupRoute: typeof RadioGroupRoute
  SliderRoute: typeof SliderRoute
  SnackbarRoute: typeof SnackbarRoute
  SubHeaderRoute: typeof SubHeaderRoute
  TabMenuRoute: typeof TabMenuRoute
  ToggleRoute: typeof ToggleRoute
  TooltipRoute: typeof TooltipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accordion': {
      id: '/accordion'
      path: '/accordion'
      fullPath: '/accordion'
      preLoaderRoute: typeof AccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-detail': {
      id: '/box-detail'
      path: '/box-detail'
      fullPath: '/box-detail'
      preLoaderRoute: typeof BoxDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button': {
      id: '/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkbox': {
      id: '/checkbox'
      path: '/checkbox'
      fullPath: '/checkbox'
      preLoaderRoute: typeof CheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chip': {
      id: '/chip'
      path: '/chip'
      fullPath: '/chip'
      preLoaderRoute: typeof ChipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clickable-option': {
      id: '/clickable-option'
      path: '/clickable-option'
      fullPath: '/clickable-option'
      preLoaderRoute: typeof ClickableOptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-tooltip': {
      id: '/copy-tooltip'
      path: '/copy-tooltip'
      fullPath: '/copy-tooltip'
      preLoaderRoute: typeof CopyTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-card': {
      id: '/customer-card'
      path: '/customer-card'
      fullPath: '/customer-card'
      preLoaderRoute: typeof CustomerCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date-picker': {
      id: '/date-picker'
      path: '/date-picker'
      fullPath: '/date-picker'
      preLoaderRoute: typeof DatePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropdown': {
      id: '/dropdown'
      path: '/dropdown'
      fullPath: '/dropdown'
      preLoaderRoute: typeof DropdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empty-page': {
      id: '/empty-page'
      path: '/empty-page'
      fullPath: '/empty-page'
      preLoaderRoute: typeof EmptyPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-icon': {
      id: '/group-icon'
      path: '/group-icon'
      fullPath: '/group-icon'
      preLoaderRoute: typeof GroupIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input-stepper': {
      id: '/input-stepper'
      path: '/input-stepper'
      fullPath: '/input-stepper'
      preLoaderRoute: typeof InputStepperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/label': {
      id: '/label'
      path: '/label'
      fullPath: '/label'
      preLoaderRoute: typeof LabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-item': {
      id: '/list-item'
      path: '/list-item'
      fullPath: '/list-item'
      preLoaderRoute: typeof ListItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modal': {
      id: '/modal'
      path: '/modal'
      fullPath: '/modal'
      preLoaderRoute: typeof ModalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview-item': {
      id: '/overview-item'
      path: '/overview-item'
      fullPath: '/overview-item'
      preLoaderRoute: typeof OverviewItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-title': {
      id: '/page-title'
      path: '/page-title'
      fullPath: '/page-title'
      preLoaderRoute: typeof PageTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress-bar': {
      id: '/progress-bar'
      path: '/progress-bar'
      fullPath: '/progress-bar'
      preLoaderRoute: typeof ProgressBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio-group': {
      id: '/radio-group'
      path: '/radio-group'
      fullPath: '/radio-group'
      preLoaderRoute: typeof RadioGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slider': {
      id: '/slider'
      path: '/slider'
      fullPath: '/slider'
      preLoaderRoute: typeof SliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snackbar': {
      id: '/snackbar'
      path: '/snackbar'
      fullPath: '/snackbar'
      preLoaderRoute: typeof SnackbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-header': {
      id: '/sub-header'
      path: '/sub-header'
      fullPath: '/sub-header'
      preLoaderRoute: typeof SubHeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tab-menu': {
      id: '/tab-menu'
      path: '/tab-menu'
      fullPath: '/tab-menu'
      preLoaderRoute: typeof TabMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toggle': {
      id: '/toggle'
      path: '/toggle'
      fullPath: '/toggle'
      preLoaderRoute: typeof ToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tooltip': {
      id: '/tooltip'
      path: '/tooltip'
      fullPath: '/tooltip'
      preLoaderRoute: typeof TooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccordionRoute: AccordionRoute,
  AvatarRoute: AvatarRoute,
  BoxDetailRoute: BoxDetailRoute,
  ButtonRoute: ButtonRoute,
  CheckboxRoute: CheckboxRoute,
  ChipRoute: ChipRoute,
  ClickableOptionRoute: ClickableOptionRoute,
  CopyTooltipRoute: CopyTooltipRoute,
  CustomerCardRoute: CustomerCardRoute,
  DatePickerRoute: DatePickerRoute,
  DropdownRoute: DropdownRoute,
  EmptyPageRoute: EmptyPageRoute,
  FieldRoute: FieldRoute,
  GroupIconRoute: GroupIconRoute,
  InputStepperRoute: InputStepperRoute,
  LabelRoute: LabelRoute,
  ListItemRoute: ListItemRoute,
  ModalRoute: ModalRoute,
  OverviewItemRoute: OverviewItemRoute,
  PageTitleRoute: PageTitleRoute,
  ProgressBarRoute: ProgressBarRoute,
  RadioGroupRoute: RadioGroupRoute,
  SliderRoute: SliderRoute,
  SnackbarRoute: SnackbarRoute,
  SubHeaderRoute: SubHeaderRoute,
  TabMenuRoute: TabMenuRoute,
  ToggleRoute: ToggleRoute,
  TooltipRoute: TooltipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
