/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ButtonRouteImport } from './routes/button'
import { Route as DropdownRouteImport } from './routes/dropdown'
import { Route as SnackbarRouteImport } from './routes/snackbar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonRoute = ButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => rootRouteImport,
} as any)
const DropdownRoute = DropdownRouteImport.update({
  id: '/dropdown',
  path: '/dropdown',
  getParentRoute: () => rootRouteImport,
} as any)
const SnackbarRoute = SnackbarRouteImport.update({
  id: '/snackbar',
  path: '/snackbar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/button': typeof ButtonRoute
  '/dropdown': typeof DropdownRoute
  '/snackbar': typeof SnackbarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/button': typeof ButtonRoute
  '/dropdown': typeof DropdownRoute
  '/snackbar': typeof SnackbarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/button': typeof ButtonRoute
  '/dropdown': typeof DropdownRoute
  '/snackbar': typeof SnackbarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/button' | '/dropdown' | '/snackbar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/button' | '/dropdown' | '/snackbar'
  id: '__root__' | '/' | '/button' | '/dropdown' | '/snackbar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtonRoute: typeof ButtonRoute
  DropdownRoute: typeof DropdownRoute
  SnackbarRoute: typeof SnackbarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button': {
      id: '/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropdown': {
      id: '/dropdown'
      path: '/dropdown'
      fullPath: '/dropdown'
      preLoaderRoute: typeof DropdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snackbar': {
      id: '/snackbar'
      path: '/snackbar'
      fullPath: '/snackbar'
      preLoaderRoute: typeof SnackbarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtonRoute: ButtonRoute,
  DropdownRoute: DropdownRoute,
  SnackbarRoute: SnackbarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
